name: wbc2026
version: "1.0.0"
config-version: 2

profile: wbc2026

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  wbc2026:
    marts:
      +materialized: table
      +schema: marts
